"""add priority column to todoitem table

Revision ID: 2d39029cac08
Revises: 
Create Date: 2026-01-12 17:19:21.935088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d39029cac08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with a default value
    op.add_column('todoitem', sa.Column('priority', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todoitem', 'priority')
    # ### end Alembic commands ###