"""update priority column to store string values low, medium, high

Revision ID: 4f637488a4e0
Revises: 6fbc838b3c2c
Create Date: 2026-01-12 19:09:46.713998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f637488a4e0'
down_revision: Union[str, None] = '6fbc838b3c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todoitem', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='priorityenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'LOW'::priorityenum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todoitem', 'priority',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='priorityenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'LOW'::priorityenum"))
    # ### end Alembic commands ###