"""update priority column to use string values low, medium, high

Revision ID: 6fbc838b3c2c
Revises: 2d39029cac08
Create Date: 2026-01-12 17:24:30.529445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fbc838b3c2c'
down_revision: Union[str, None] = '2d39029cac08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    priority_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priorityenum')
    priority_enum.create(op.get_bind(), checkfirst=True)

    # Add a new temporary column with the enum type
    op.add_column('todoitem', sa.Column('priority_temp', priority_enum,
                                       server_default='LOW', nullable=False))

    # Update the new column with string values based on the integer values
    # Map numeric priorities to string equivalents
    op.execute("""
        UPDATE todoitem
        SET priority_temp = CASE
            WHEN priority IN (1, 2) THEN 'LOW'::priorityenum
            WHEN priority = 3 THEN 'MEDIUM'::priorityenum
            WHEN priority IN (4, 5) THEN 'HIGH'::priorityenum
            ELSE 'LOW'::priorityenum
        END
    """)

    # Drop the old column
    op.drop_column('todoitem', 'priority')

    # Rename the new column to priority
    op.alter_column('todoitem', 'priority_temp', new_column_name='priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add a temporary integer column
    op.add_column('todoitem', sa.Column('priority_temp', sa.Integer(),
                                        server_default='1', nullable=False))

    # Map string priorities back to integer values
    op.execute("""
        UPDATE todoitem
        SET priority_temp = CASE
            WHEN priority = 'LOW' THEN 1
            WHEN priority = 'MEDIUM' THEN 3
            WHEN priority = 'HIGH' THEN 5
            ELSE 1
        END
    """)

    # Drop the old column
    op.drop_column('todoitem', 'priority')

    # Rename the new column to priority
    op.alter_column('todoitem', 'priority_temp', new_column_name='priority')

    # Drop the enum type
    priority_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priorityenum')
    priority_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###