openapi: 3.0.3
info:
  title: Todo Application API
  description: API for the Todo application with Better Auth integration
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.com
    description: Production server
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  minLength: 8
                  description: User's password (min 8 chars with upper, lower, number, special)
                  example: "SecurePass123!"
                first_name:
                  type: string
                  maxLength: 100
                  description: User's first name (optional)
                last_name:
                  type: string
                  maxLength: 100
                  description: User's last name (optional)
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User registered successfully"
                  token:
                    type: string
                    description: JWT token for authentication
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/auth/login:
    post:
      summary: Authenticate user and return JWT token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  description: User's password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Account inactive
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/auth/logout:
    post:
      summary: Logout user (invalidate session)
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully logged out
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/todos:
    get:
      summary: Get all todos for authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [active, completed, all]
            default: all
          description: Filter todos by status
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Todo'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new todo for authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  maxLength: 255
                  description: Title of the todo
                description:
                  type: string
                  maxLength: 10000
                  description: Detailed description of the todo (optional)
      responses:
        '201':
          description: Todo created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/todos/{id}:
    put:
      summary: Update a todo for authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the todo to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 255
                  description: Title of the todo (optional)
                description:
                  type: string
                  maxLength: 10000
                  description: Detailed description of the todo (optional)
                is_completed:
                  type: boolean
                  description: Completion status (optional)
      responses:
        '200':
          description: Todo updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a todo for authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the todo to delete
      responses:
        '204':
          description: Todo deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/todos/logs:
    get:
      summary: Get activity logs for authenticated user
      tags:
        - Logs
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Number of items per page
        - name: action
          in: query
          required: false
          schema:
            type: string
            enum: [CREATE, UPDATE, DELETE]
          description: Filter logs by action type
      responses:
        '200':
          description: List of log entries
          content:
            application/json:
              schema:
                type: object
                properties:
                  logs:
                    type: array
                    items:
                      $ref: '#/components/schemas/TodoLog'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the todo
        title:
          type: string
          description: Title of the todo
        description:
          type: string
          description: Detailed description of the todo
        is_completed:
          type: boolean
          description: Completion status
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this todo
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
        completed_at:
          type: string
          format: date-time
          description: Completion timestamp (if completed)
      required:
        - id
        - title
        - is_completed
        - user_id
        - created_at
        - updated_at
    TodoLog:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the log entry
        action:
          type: string
          enum: [CREATE, UPDATE, DELETE]
          description: Type of action performed
        todo_id:
          type: string
          format: uuid
          description: ID of the todo affected (if applicable)
        user_id:
          type: string
          format: uuid
          description: ID of the user who performed the action
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the action was performed
        previous_state:
          type: object
          description: Previous state of the todo (for UPDATE actions)
        new_state:
          type: object
          description: New state of the todo (for CREATE/UPDATE actions)
      required:
        - id
        - action
        - user_id
        - timestamp
    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: Current page number
        limit:
          type: integer
          description: Number of items per page
        total:
          type: integer
          description: Total number of items
        total_pages:
          type: integer
          description: Total number of pages
      required:
        - page
        - limit
        - total
        - total_pages
    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message
      required:
        - detail